### ISSUE TITLE
Plugins not being downloaded in a study

### ISSUE THREAD

**Issue by JulioV** [denzilferreira/aware-client#109]
If a study has plugins that need to be download and the user clicks on "Install" in the joining screen, the client goes to the play store instead to the study's URL

**Comment by JHamberg** [comment]
I'd like to add that this issue seems to apply to studies on self-hosted aware-servers. As long as the _Study URL_ preference is changed to correspond with the new domain name in the _Study and sync settings_, the plugin downloads properly. This is, however, quite clumsy as users joining the study would first have to change this setting and only then attempt to join the study.

**Comment by denzilferreira** [comment]
Fixed.
